M48
; DRILL file {KiCad (7.0.0)} date Tue Jun 13 12:49:36 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-06-13T12:49:36+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.500
%
G90
G05
T1
X129.25Y-104.4
X129.75Y-66.3
X174.0Y-104.125
X174.425Y-66.375
T0
M30
